import {DAYS,newId,validCourse,validDate} from './planner';
import type {Course,Planner,Task} from './planner';
import {Actions,Modal} from './surfaces';
import type {Checkpoint,Editor,Update} from './surfaces';

export function Editors({editor,setEditor,data,today,update,checkpoint,setNotice,addTask,pick}:{editor:Editor;setEditor:(e:Editor|null)=>void;data:Planner;today:string;update:Update;checkpoint:Checkpoint;setNotice:(s:string)=>void;addTask:(title:string,options?:Partial<Task>,choose?:boolean)=>Task|undefined;pick:(t:Task)=>void}){
  const close=()=>setEditor(null);
  if(editor.kind==='task'){
    const t=editor.value,set=(patch:Partial<typeof t>)=>setEditor({kind:'task',value:{...t,...patch}});
    return <Modal title="编辑任务" onClose={close}><label>要做什么<input value={t.title} onChange={e=>set({title:e.target.value})}/></label><label>这次的一小步（可留空）<input value={t.step??''} onChange={e=>set({step:e.target.value})}/></label><div className="form-row"><label>预计分钟（0 表示不估计）<input type="number" min="0" max="1440" value={t.minutes} onChange={e=>set({minutes:Number(e.target.value)})}/></label><label>所属事项<input value={t.project} onChange={e=>set({project:e.target.value})}/></label></div><Actions onDelete={()=>{checkpoint(d=>({...d,tasks:d.tasks.filter(x=>x.id!==t.id)}),'任务已移除，可撤销。');close()}} onSave={()=>{if(!t.title.trim()||!Number.isFinite(t.minutes)||t.minutes<0||t.minutes>1440){setNotice('请确认任务名称和预计时间。');return}const task={...t,title:t.title.trim()};update(d=>({...d,tasks:d.tasks.map(x=>x.id===t.id?task:x),projects:d.projects.map(p=>p.id===t.projectId?{...p,todos:p.todos.map(x=>x.id===t.projectTodoId?{...x,title:task.title}:x)}:p)}));close()}}/></Modal>;
  }
  if(editor.kind==='project'){
    const p=editor.value,set=(patch:Partial<typeof p>)=>setEditor({kind:'project',value:{...p,...patch}});
    const save=()=>{if(!p.name.trim()){setNotice('请填写项目名称。');return false}const project={...p,name:p.name.trim()};update(d=>({...d,projects:d.projects.some(x=>x.id===p.id)?d.projects.map(x=>x.id===p.id?project:x):[...d.projects,project],tasks:d.tasks.map(t=>{if(t.projectId!==p.id)return t;const todo=p.todos.find(x=>x.id===t.projectTodoId);return todo?{...t,title:todo.title,done:todo.done,project:p.name,completedAt:todo.done?(t.completedAt??today):undefined}:{...t,project:p.name,projectTodoId:undefined}})}));return true};
    return <Modal title="项目与下一步" onClose={close} wide><label>项目名称<input value={p.name} onChange={e=>set({name:e.target.value})}/></label><div className="form-row"><label>状态<select value={p.status??'active'} onChange={e=>set({status:e.target.value as typeof p.status})}><option value="active">进行中</option><option value="waiting">等待中</option><option value="paused">暂时放下</option><option value="done">完成</option></select></label><label>下次再看（可留空）<input type="date" value={p.revisit??''} onChange={e=>set({revisit:e.target.value})}/></label></div><label>当前进展<textarea value={p.progress??''} onChange={e=>set({progress:e.target.value})} placeholder="上次做到哪里了"/></label><label>下一步<input value={p.next??p.mainline} onChange={e=>set({next:e.target.value})}/></label>{p.status==='waiting'&&<label>等谁提供什么<input value={p.waiting??''} onChange={e=>set({waiting:e.target.value})}/></label>}<details className="inline-details"><summary>项目笔记与任务</summary><label>主线<input value={p.mainline} onChange={e=>set({mainline:e.target.value})}/></label><label>笔记<textarea value={p.note} onChange={e=>set({note:e.target.value})}/></label>{p.todos.map(t=><div className="todo-edit" key={t.id}><input type="checkbox" aria-label={'完成：'+t.title} checked={t.done} onChange={e=>set({todos:p.todos.map(x=>x.id===t.id?{...x,done:e.target.checked}:x)})}/><input aria-label="任务名称" value={t.title} onChange={e=>set({todos:p.todos.map(x=>x.id===t.id?{...x,title:e.target.value}:x)})}/><button className="text-button" onClick={()=>{if(!t.title.trim()||!save())return;if(data.tasks.some(x=>x.projectId===p.id&&x.projectTodoId===t.id))setNotice('这一步已在收件箱里。');else{addTask(t.title,{project:p.name,projectId:p.id,projectTodoId:t.id,done:t.done,completedAt:t.done?today:undefined});setNotice('已放入收件箱。')}close()}}>放收件箱</button><button className="text-button" aria-label={'移除任务：'+t.title} onClick={()=>set({todos:p.todos.filter(x=>x.id!==t.id)})}>×</button></div>)}<button onClick={()=>set({todos:[...p.todos,{id:newId(),title:'',done:false}]})}>添加任务</button></details><Actions onDelete={()=>{checkpoint(d=>({...d,projects:d.projects.filter(x=>x.id!==p.id),tasks:d.tasks.map(t=>t.projectId===p.id?{...t,projectId:undefined,projectTodoId:undefined}:t)}),'项目已移除，收件箱的动作仍保留。');close()}} onSave={()=>{if(save())close()}}/></Modal>;
  }
  if(editor.kind==='milestone'){
    const m=editor.value,set=(patch:Partial<typeof m>)=>setEditor({kind:'milestone',value:{...m,...patch}});
    const valid=()=>!!m.title.trim()&&validDate(m.date)&&(!m.actionDate||(validDate(m.actionDate)&&m.actionDate<=m.date));
    const save=()=>{if(!valid()){setNotice('请确认名称、截止日期和开始处理日期。');return false}update(d=>({...d,milestones:d.milestones.some(x=>x.id===m.id)?d.milestones.map(x=>x.id===m.id?m:x):[...d.milestones,m]}));return true};
    return <Modal title="近期安排" onClose={close}><label>安排名称<input value={m.title} onChange={e=>set({title:e.target.value})}/></label><label>截止日期<input type="date" value={validDate(m.date)?m.date:''} onChange={e=>set({date:e.target.value})}/></label>{!validDate(m.date)&&<p className="muted">旧记录日期：{m.date}，请确认完整日期。</p>}<label>需要采取的动作<input value={m.action??''} onChange={e=>set({action:e.target.value})} placeholder="例如：检查材料是否齐全"/></label><label>从哪天开始处理（可留空）<input type="date" max={m.date} value={m.actionDate??''} onChange={e=>set({actionDate:e.target.value})}/></label><p className="muted">留空时，只在截止当天及之后提示。首页一次只显示一项。</p><label className="checkbox-label"><input type="checkbox" checked={m.done??false} onChange={e=>set({done:e.target.checked})}/>这项安排已经处理好</label><Actions onDelete={()=>{checkpoint(d=>({...d,milestones:d.milestones.filter(x=>x.id!==m.id)}),'安排已移除，可撤销。');close()}} onSave={()=>{if(save())close()}}/>{!m.done&&<button className="full-width" onClick={()=>{if(!save())return;const title=m.action?.trim()||m.title,t=data.tasks.find(t=>!t.done&&t.title===title&&t.project==='近期安排');if(t)pick(t);else addTask(title,{project:'近期安排'},true);close()}}>把这个动作选为当前事项</button>}</Modal>;
  }
  if(editor.kind==='habit'){
    const h=editor.value,set=(patch:Partial<typeof h>)=>setEditor({kind:'habit',value:{...h,...patch}});
    return <Modal title="固定安排" onClose={close}><label>名称<input value={h.title} onChange={e=>set({title:e.target.value})}/></label><label>星期<select value={h.day} onChange={e=>set({day:Number(e.target.value)})}>{DAYS.map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select></label><label>时段<select value={h.breakTime??'period'} onChange={e=>set({breakTime:e.target.value==='period'?undefined:e.target.value as 'lunch'|'dinner'})}><option value="period">按节次安排</option><option value="lunch">午间休息</option><option value="dinner">晚间休息</option></select></label>{!h.breakTime&&<div className="form-row"><label>开始节次<input type="number" min="1" max="14" value={h.period} onChange={e=>set({period:Number(e.target.value)})}/></label><label>持续节数<input type="number" min="1" max="14" value={h.span} onChange={e=>set({span:Number(e.target.value)})}/></label></div>}<div className="form-row"><label>开始日期<input type="date" value={h.startDate} onChange={e=>set({startDate:e.target.value})}/></label><label>结束日期<input type="date" value={h.endDate} onChange={e=>set({endDate:e.target.value})}/></label></div><label>这段时间用来做什么<textarea value={h.note??''} onChange={e=>set({note:e.target.value})}/></label><Actions onDelete={()=>{checkpoint(d=>({...d,habits:d.habits.filter(x=>x.id!==h.id)}),'习惯已移除，可撤销。');close()}} onSave={()=>{if(!validCourse({...h,kind:'habit'} as Course)||!validDate(h.startDate)||!validDate(h.endDate)||h.endDate<h.startDate){setNotice('请确认名称、节次和日期范围。');return}update(d=>({...d,habits:d.habits.some(x=>x.id===h.id)?d.habits.map(x=>x.id===h.id?h:x):[...d.habits,h]}));close()}}/></Modal>;
  }
  const i=editor.value,set=(patch:Partial<typeof i>)=>setEditor({kind:'idea',value:{...i,...patch}});
  return <Modal title="留一个想法" onClose={close}><label>标题<input value={i.title} onChange={e=>set({title:e.target.value})}/></label><label>分类<select value={i.category} onChange={e=>set({category:e.target.value})}>{['想法','书','电影','文章','人生思考','生活 / 期待'].map(c=><option key={c}>{c}</option>)}</select></label><label>记几句话<textarea value={i.note} onChange={e=>set({note:e.target.value})}/></label><Actions onDelete={()=>{checkpoint(d=>({...d,ideas:d.ideas.filter(x=>x.id!==i.id)}),'想法已移除，可撤销。');close()}} onSave={()=>{if(!i.title.trim())return;update(d=>({...d,ideas:d.ideas.some(x=>x.id===i.id)?d.ideas.map(x=>x.id===i.id?i:x):[...d.ideas,i]}));close()}}/></Modal>;
}
