'use client';
import {useEffect,useMemo,useState} from 'react';

type Task={id:number;title:string;project:string;minutes:number;done:boolean;projectId?:number;projectTodoId?:number};
type Course={id:number;day:number;period:number;span:number;title:string;kind:'course'|'self'|'habit';habitId?:number};
type ProjectTodo={id:number;title:string;done:boolean};
type Project={id:number;name:string;color:string;mainline:string;note:string;todos:ProjectTodo[]};
type Milestone={id:number;date:string;title:string;hot:boolean};
type Habit={id:number;title:string;day:number;period:number;span:number;startDate:string;endDate:string};
type Idea={id:number;title:string;category:'想法'|'书'|'电影'|'文章'|'人生思考';note:string};
const taskSeed:Task[]=[];
const courseSeed:Course[]=[];
const projectSeed:Project[]=[];
const milestoneSeed:Milestone[]=[];
const habitSeed:Habit[]=[];
const ideaSeed:Idea[]=[];
const days=['周一','周二','周三','周四','周五','周六','周日'];
const pad=(n:number)=>String(n).padStart(2,'0');
const keyOf=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const startOfWeek=(d:Date)=>{const x=new Date(d);const day=x.getDay()||7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day+1);return x};
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};

export default function Home(){
 const[tasks,setTasks]=useState<Task[]>(taskSeed),[projects,setProjects]=useState<Project[]>(projectSeed),[milestones,setMilestones]=useState<Milestone[]>(milestoneSeed);
 const[habits,setHabits]=useState<Habit[]>(habitSeed),[ideas,setIdeas]=useState<Idea[]>(ideaSeed);
 const[schedules,setSchedules]=useState<Record<string,Course[]>>({}),[weekStart,setWeekStart]=useState(()=>startOfWeek(new Date()));
 const[now,setNow]=useState(()=>new Date());
 const[input,setInput]=useState(''),[loaded,setLoaded]=useState(false);
 const[courseEdit,setCourseEdit]=useState<Course|null>(null),[taskEdit,setTaskEdit]=useState<Task|null>(null),[projectEdit,setProjectEdit]=useState<Project|null>(null),[milestoneEdit,setMilestoneEdit]=useState<Milestone|null>(null);
 const[habitEdit,setHabitEdit]=useState<Habit|null>(null),[ideaEdit,setIdeaEdit]=useState<Idea|null>(null);
 const weekKey=keyOf(weekStart),termStart='2026-09-07';
 const defaultCourses=weekKey<termStart?[]:courseSeed;
 const manualCourses=schedules[weekKey]??defaultCourses;
 const habitCourses:Course[]=habits.filter(h=>weekKey>=keyOf(startOfWeek(new Date(h.startDate+'T00:00:00')))&&weekKey<=keyOf(startOfWeek(new Date(h.endDate+'T00:00:00')))).map(h=>({id:900000+h.id,day:h.day,period:h.period,span:h.span,title:h.title,kind:'habit',habitId:h.id}));
 const courses=[...manualCourses,...habitCourses];
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register(new URL('sw.js',document.baseURI).pathname);const t=localStorage.getItem('daylight-tasks'),w=localStorage.getItem('daylight-weekly-schedules'),p=localStorage.getItem('daylight-projects'),m=localStorage.getItem('daylight-milestones'),h=localStorage.getItem('daylight-habits'),i=localStorage.getItem('daylight-ideas');
  if(t)setTasks(JSON.parse(t));
  if(w){const parsed=JSON.parse(w) as Record<string,Course[]>;Object.keys(parsed).forEach(k=>{if(k<termStart)parsed[k]=parsed[k].filter(c=>c.kind==='self')});setSchedules(parsed)}
  if(p){const parsed=JSON.parse(p) as Array<Project&{next?:string}>;setProjects(parsed.map(x=>({id:x.id,name:x.name,color:x.color,mainline:x.mainline??x.next??'',note:x.note,todos:Array.isArray(x.todos)?x.todos:[]})))}
  if(m)setMilestones(JSON.parse(m));if(h)setHabits(JSON.parse(h));if(i)setIdeas(JSON.parse(i));setLoaded(true)},[]);
 useEffect(()=>{if(!loaded)return;localStorage.setItem('daylight-tasks',JSON.stringify(tasks));localStorage.setItem('daylight-weekly-schedules',JSON.stringify(schedules));localStorage.setItem('daylight-projects',JSON.stringify(projects));localStorage.setItem('daylight-milestones',JSON.stringify(milestones));localStorage.setItem('daylight-habits',JSON.stringify(habits));localStorage.setItem('daylight-ideas',JSON.stringify(ideas))},[tasks,schedules,projects,milestones,habits,ideas,loaded]);
 useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),60000);return()=>window.clearInterval(timer)},[]);
 const minutes=useMemo(()=>tasks.filter(t=>!t.done).reduce((a,t)=>a+t.minutes,0),[tasks]);
 const setWeekCourses=(next:Course[])=>setSchedules({...schedules,[weekKey]:next.filter(c=>c.kind!=='habit')});
 const addTask=()=>{if(!input.trim())return;setTasks([...tasks,{id:Date.now(),title:input.trim(),project:'临时收件箱',minutes:30,done:false}]);setInput('')};
 const toggleTask=(task:Task)=>{const done=!task.done;setTasks(tasks.map(t=>t.id===task.id?{...t,done}:t));if(task.projectId&&task.projectTodoId)setProjects(projects.map(p=>p.id===task.projectId?{...p,todos:p.todos.map(x=>x.id===task.projectTodoId?{...x,done}:x)}:p))};
 const toggleProjectTodo=(projectId:number,todoId:number)=>{const p=projects.find(x=>x.id===projectId),todo=p?.todos.find(x=>x.id===todoId);if(!todo)return;const done=!todo.done;setProjects(projects.map(x=>x.id===projectId?{...x,todos:x.todos.map(t=>t.id===todoId?{...t,done}:t)}:x));setTasks(tasks.map(t=>t.projectId===projectId&&t.projectTodoId===todoId?{...t,done}:t))};
 const addTodoToToday=(project:Project,todo:ProjectTodo)=>{if(tasks.some(t=>t.projectId===project.id&&t.projectTodoId===todo.id))return;setTasks([...tasks,{id:Date.now(),title:todo.title,project:project.name,minutes:45,done:todo.done,projectId:project.id,projectTodoId:todo.id}])};
 const saveProject=()=>{if(!projectEdit||!projectEdit.name.trim())return;setProjects([...projects.filter(p=>p.id!==projectEdit.id),projectEdit]);setTasks(tasks.filter(t=>t.projectId!==projectEdit.id||projectEdit.todos.some(x=>x.id===t.projectTodoId)).map(t=>{if(t.projectId!==projectEdit.id)return t;const linked=projectEdit.todos.find(x=>x.id===t.projectTodoId);return {...t,project:projectEdit.name,title:linked?.title??t.title}}));setProjectEdit(null)};
 const saveTask=()=>{if(!taskEdit)return;setTasks(tasks.map(t=>t.id===taskEdit.id?taskEdit:t));if(taskEdit.projectId&&taskEdit.projectTodoId)setProjects(projects.map(p=>p.id===taskEdit.projectId?{...p,todos:p.todos.map(x=>x.id===taskEdit.projectTodoId?{...x,title:taskEdit.title,done:taskEdit.done}:x)}:p));setTaskEdit(null)};
 const openCell=(day:number,period:number)=>{const found=courses.find(c=>c.day===day&&period>=c.period&&period<c.period+c.span);if(found?.kind==='habit'){const h=habits.find(x=>x.id===found.habitId);if(h)setHabitEdit({...h});return}setCourseEdit(found?{...found}:{id:Date.now(),day,period,span:1,title:'',kind:'self'})};
 const fmt=(d:Date)=>`${d.getMonth()+1}/${d.getDate()}`;
 const extendHabit=(weeks:number,months:number)=>{if(!habitEdit?.startDate)return;const d=new Date(habitEdit.startDate+'T00:00:00');if(weeks)d.setDate(d.getDate()+weeks*7-1);if(months){d.setMonth(d.getMonth()+months);d.setDate(d.getDate()-1)}setHabitEdit({...habitEdit,endDate:keyOf(d)})};
 const weekEnd=addDays(weekStart,6);
 const weekOffset=Math.round((weekStart.getTime()-new Date(2026,8,7).getTime())/604800000);
 const weekLabel=weekOffset<0?`暑假第${11+weekOffset}周`:`秋季学期第${weekOffset+1}周`;
 const dateLabel=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(now);
 const greeting=now.getHours()<11?'早上好':now.getHours()<18?'下午好':'晚上好';
 return <main>
  <header className="topbar"><div className="brand"><span className="sun">☀</span><strong>有序</strong></div><div className="date">{dateLabel}</div><button className="quiet" onClick={()=>document.getElementById('inbox')?.focus()}>＋ 快速记一件事</button></header>
  <div className="shell"><aside className="sidebar"><p className="eyebrow">这段时间</p><h2>先稳住节奏，<br/>再完成大事。</h2><nav><a className="active" href="#today">今天</a><a href="#schedule">每周课表</a><a href="#projects">项目全景</a><a href="#habits">养习惯</a><a href="#ideas">奇思妙想</a><a href="#rhythm">近期节奏</a></nav><div className="rule"><span>规划原则</span><p>每天 3 件关键事。做完就算今天成功，不用清空所有待办。</p></div></aside>
  <section className="content">
   <section id="today" className="hero"><div><p className="eyebrow green">今天只看这里</p><h1>{greeting}。今天的容量<br/>已经替你守住了。</h1><p className="sub">安排约 {minutes} 分钟，留出缓冲。不需要同时想完所有项目。</p></div><div className="capacity"><div className="ring"><span>{tasks.filter(t=>!t.done).length}</span><small>件关键事</small></div></div></section>
   <section className="today-card"><div className="section-head"><div><p className="eyebrow">TODAY · 今日清单</p><h3>完成这些，今天就够了</h3></div><span>{tasks.filter(t=>t.done).length}/{tasks.length} 已完成</span></div><div className="tasks">{tasks.length===0?<p className="empty-note">今天还没有安排。先写下一件最想推进的小事。</p>:tasks.map((task,i)=><div className={'task '+(task.done?'done':'')} key={task.id}><button aria-label="标记完成" className="check" onClick={()=>toggleTask(task)}>{task.done?'✓':i+1}</button><button className="task-copy editable-copy" onClick={()=>setTaskEdit({...task})}><b>{task.title}</b><span>{task.project}{task.projectTodoId?' · 已关联项目待办':''}</span></button><span className="duration">{task.minutes} 分钟</span><button className="focus" onClick={()=>setTaskEdit({...task})}>编辑</button></div>)}</div><div className="inbox-row"><input id="inbox" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addTask()} placeholder="新增一件今天要做的事"/><button onClick={addTask}>添加</button></div></section>

   <section id="schedule" className="schedule-section"><div className="section-head schedule-title"><div><p className="eyebrow">WEEK · {weekLabel}</p><h3>{fmt(weekStart)}–{fmt(weekEnd)} 的安排</h3></div><div className="week-nav"><button onClick={()=>setWeekStart(addDays(weekStart,-7))}>← 上周</button><button onClick={()=>setWeekStart(startOfWeek(new Date()))}>本周</button><button onClick={()=>setWeekStart(addDays(weekStart,7))}>下周 →</button></div></div>
    <div className="schedule-wrap"><div className="schedule-grid">
     <div className="corner sticky-col" style={{gridColumn:1,gridRow:1}}>节次</div>
     {days.map((d,i)=>{const date=addDays(weekStart,i);return <div className={'day-head '+(keyOf(date)===keyOf(now)?'is-today':'')} style={{gridColumn:i+2,gridRow:1}} key={d}><b>{d}</b><small>{fmt(date)}</small></div>})}
     {Array.from({length:14},(_,pi)=>{const period=pi+1;return <div className={'period sticky-col '+(period===6?'lunch-gap':'')+(period===11?' evening-gap':'')} style={{gridColumn:1,gridRow:period+1}} key={'p'+period}>{period}</div>})}
     {Array.from({length:14},(_,pi)=>days.map((_,di)=>{const period=pi+1,day=di+1;return <button aria-label={days[di]+'第'+period+'节'} className={'schedule-slot '+(period===6?'lunch-gap':'')+(period===11?' evening-gap':'')} style={{gridColumn:day+1,gridRow:period+1}} key={'slot-'+day+'-'+period} onClick={()=>openCell(day,period)}/> }))}
     {courses.map(c=><button className={'course-block '+c.kind} key={c.kind+'-'+c.id} style={{gridColumn:c.day+1,gridRow:`${c.period+1} / span ${c.span}`}} onClick={()=>openCell(c.day,c.period)}><b>{c.title}</b><small>{c.span>1?c.span+' 节':''}{c.kind==='habit'?' · 习惯':''}</small></button>)}
    </div></div><div className="schedule-legend"><span><i className="course-dot"/>学校课程</span><span><i className="self-dot"/>自己的安排</span><span><i className="habit-dot"/>习惯</span><button onClick={()=>setWeekCourses(defaultCourses.map(c=>({...c})))}>恢复本周</button></div>
   </section>

   <section id="projects" className="projects-section"><div className="section-head"><div><p className="eyebrow">PROJECTS · 项目全景</p><h3>沿着主线，一步一步推进</h3></div><button className="add-small" onClick={()=>setProjectEdit({id:Date.now(),name:'',color:'#6f7c62',mainline:'',note:'',todos:[]})}>＋ 新建项目</button></div><div className="project-grid">{projects.length===0?<button className="empty-card" onClick={()=>setProjectEdit({id:Date.now(),name:'',color:'#6f7c62',mainline:'',note:'',todos:[]})}><span>＋</span><b>建立第一个项目</b><small>把长期目标拆成可以完成的待办</small></button>:projects.map(p=>{const done=p.todos.filter(t=>t.done).length,total=p.todos.length;return <button className="project project-button" key={p.id} onClick={()=>setProjectEdit({...p,todos:p.todos.map(t=>({...t}))})} style={{'--accent':p.color} as React.CSSProperties}><div className="project-top"><span className="dot"/><small>{p.note||'点击进入'}</small></div><h4>{p.name}</h4><p>{p.mainline||'还没有设置主线'}</p>{total>0?<><div className="bar"><i style={{width:(done/total*100)+'%'}}/></div><span className="percent">{done}/{total} 项待办已完成 · 点击进入</span></>:<span className="percent no-progress">打开项目添加待办</span>}</button>})}</div></section>
   <section id="habits" className="habits-section"><div className="section-head"><div><p className="eyebrow">HABITS · 养习惯</p><h3>让想坚持的事，准时出现在每一周</h3></div><button className="add-small" onClick={()=>setHabitEdit({id:Date.now(),title:'',day:1,period:1,span:1,startDate:weekKey,endDate:keyOf(addDays(weekStart,27))})}>＋ 新习惯</button></div><div className="habit-grid">{habits.length===0?<button className="empty-card" onClick={()=>setHabitEdit({id:Date.now(),title:'',day:1,period:1,span:1,startDate:weekKey,endDate:keyOf(addDays(weekStart,27))})}><span>＋</span><b>安排第一个习惯</b><small>例如每周两次 OS 自学</small></button>:habits.map(h=><button className="habit-card" key={h.id} onClick={()=>setHabitEdit({...h})}><span className="habit-mark">↻</span><div><b>{h.title}</b><p>{days[h.day-1]} · 第 {h.period}–{h.period+h.span-1} 节</p><small>{h.startDate.replaceAll('-','.')} — {h.endDate.replaceAll('-','.')}</small></div></button>)}</div></section>
   <section id="ideas" className="ideas-section"><div className="section-head"><div><p className="eyebrow">IDEAS · 奇思妙想</p><h3>先把闪过脑海的东西接住</h3></div><button className="add-small" onClick={()=>setIdeaEdit({id:Date.now(),title:'',category:'想法',note:''})}>＋ 记一个</button></div><div className="idea-grid">{ideas.length===0?<button className="empty-card" onClick={()=>setIdeaEdit({id:Date.now(),title:'',category:'想法',note:''})}><span>✦</span><b>这里还很空，正好用来胡思乱想</b><small>想看的书、电影、文章和人生问题都可以放进来</small></button>:ideas.map(i=><button className="idea-card" key={i.id} onClick={()=>setIdeaEdit({...i})}><small>{i.category}</small><b>{i.title}</b><p>{i.note||'点开继续想'}</p></button>)}</div></section>
   <section id="rhythm" className="timeline"><div className="section-head"><div><p className="eyebrow">RHYTHM · 近期节奏</p><h3>把真正会改变安排的节点放在这里</h3></div><button className="add-small" onClick={()=>setMilestoneEdit({id:Date.now(),date:'',title:'',hot:false})}>＋ 添加节点</button></div><div className="timeline-row">{milestones.length===0?<button className="empty-card" onClick={()=>setMilestoneEdit({id:Date.now(),date:'',title:'',hot:false})}><span>＋</span><b>添加近期节点</b><small>考试、截止日期和忙碌阶段都可以放在这里</small></button>:milestones.map(m=><button key={m.id} className={m.hot?'hot':''} onClick={()=>setMilestoneEdit({...m})}><b>{m.date}</b><span>{m.title}</span><small>点击编辑</small></button>)}</div></section>
  </section></div>

  {courseEdit&&<Modal title={days[courseEdit.day-1]+' · 第 '+courseEdit.period+' 节'} onClose={()=>setCourseEdit(null)}><label>名称<input autoFocus value={courseEdit.title} onChange={e=>setCourseEdit({...courseEdit,title:e.target.value})} placeholder="例如：OS 自学"/></label><div className="form-row"><label>开始节次<input type="number" min="1" max="14" value={courseEdit.period} onChange={e=>setCourseEdit({...courseEdit,period:+e.target.value})}/></label><label>持续节数<input type="number" min="1" max="4" value={courseEdit.span} onChange={e=>setCourseEdit({...courseEdit,span:+e.target.value})}/></label></div><label>类型<select value={courseEdit.kind} onChange={e=>setCourseEdit({...courseEdit,kind:e.target.value as Course['kind']})}><option value="course">学校课程</option><option value="self">自学 / 自己安排</option></select></label><Actions onDelete={()=>{setWeekCourses(courses.filter(c=>c.id!==courseEdit.id));setCourseEdit(null)}} onCancel={()=>setCourseEdit(null)} onSave={()=>{if(courseEdit.title.trim())setWeekCourses([...courses.filter(c=>c.id!==courseEdit.id),{...courseEdit,title:courseEdit.title.trim()}]);setCourseEdit(null)}}/></Modal>}
  {taskEdit&&<Modal title="编辑今日事项" onClose={()=>setTaskEdit(null)}><label>事项<input autoFocus value={taskEdit.title} onChange={e=>setTaskEdit({...taskEdit,title:e.target.value})}/></label><label>所属项目<input value={taskEdit.project} onChange={e=>setTaskEdit({...taskEdit,project:e.target.value})}/></label><label>预计分钟<input type="number" min="5" step="5" value={taskEdit.minutes} onChange={e=>setTaskEdit({...taskEdit,minutes:+e.target.value})}/></label>{taskEdit.projectTodoId&&<p className="linked-note">这条事项与项目待办相连，标题和完成状态会同步。</p>}<Actions onDelete={()=>{setTasks(tasks.filter(t=>t.id!==taskEdit.id));setTaskEdit(null)}} onCancel={()=>setTaskEdit(null)} onSave={saveTask}/></Modal>}
  {projectEdit&&<Modal title={projectEdit.name||'新项目'} onClose={()=>setProjectEdit(null)} wide><div className="form-row"><label>项目名称<input autoFocus value={projectEdit.name} onChange={e=>setProjectEdit({...projectEdit,name:e.target.value})}/></label><label>状态短句<input value={projectEdit.note} onChange={e=>setProjectEdit({...projectEdit,note:e.target.value})} placeholder="例如：当前主线"/></label></div><label>项目主线<textarea value={projectEdit.mainline} onChange={e=>setProjectEdit({...projectEdit,mainline:e.target.value})} placeholder="写清楚这个项目接下来沿什么路径推进"/></label><div className="project-todo-head"><b>项目待办</b><button type="button" onClick={()=>setProjectEdit({...projectEdit,todos:[...projectEdit.todos,{id:Date.now(),title:'新待办',done:false}]})}>＋ 添加待办</button></div><div className="project-todos">{projectEdit.todos.map(todo=><div className="project-todo" key={todo.id}><button type="button" className={'mini-check '+(todo.done?'checked':'')} onClick={()=>{const done=!todo.done;setProjectEdit({...projectEdit,todos:projectEdit.todos.map(t=>t.id===todo.id?{...t,done}:t)});if(projects.some(p=>p.id===projectEdit.id))toggleProjectTodo(projectEdit.id,todo.id)}}>{todo.done?'✓':''}</button><input value={todo.title} onChange={e=>setProjectEdit({...projectEdit,todos:projectEdit.todos.map(t=>t.id===todo.id?{...t,title:e.target.value}:t)})}/><button type="button" className="to-today" onClick={()=>addTodoToToday(projectEdit,todo)}>{tasks.some(t=>t.projectId===projectEdit.id&&t.projectTodoId===todo.id)?'已在今日':'＋ 今日'}</button><button type="button" className="remove-todo" onClick={()=>setProjectEdit({...projectEdit,todos:projectEdit.todos.filter(t=>t.id!==todo.id)})}>×</button></div>)}</div><label>标记颜色<input type="color" value={projectEdit.color} onChange={e=>setProjectEdit({...projectEdit,color:e.target.value})}/></label><Actions onDelete={()=>{setProjects(projects.filter(p=>p.id!==projectEdit.id));setTasks(tasks.filter(t=>t.projectId!==projectEdit.id));setProjectEdit(null)}} onCancel={()=>setProjectEdit(null)} onSave={saveProject}/></Modal>}
  {habitEdit&&<Modal title={habitEdit.title||'新习惯'} onClose={()=>setHabitEdit(null)}><label>想养成什么习惯<input autoFocus value={habitEdit.title} onChange={e=>setHabitEdit({...habitEdit,title:e.target.value})} placeholder="例如：学习 OS"/></label><div className="form-row"><label>星期<select value={habitEdit.day} onChange={e=>setHabitEdit({...habitEdit,day:+e.target.value})}>{days.map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label><label>开始节次<input type="number" min="1" max="14" value={habitEdit.period} onChange={e=>setHabitEdit({...habitEdit,period:+e.target.value})}/></label></div><label>持续节数<input type="number" min="1" max="4" value={habitEdit.span} onChange={e=>setHabitEdit({...habitEdit,span:+e.target.value})}/></label><div className="form-row"><label>从哪天开始<input type="date" value={habitEdit.startDate} onChange={e=>setHabitEdit({...habitEdit,startDate:e.target.value})}/></label><label>维持到<input type="date" value={habitEdit.endDate} onChange={e=>setHabitEdit({...habitEdit,endDate:e.target.value})}/></label></div><div className="duration-shortcuts"><span>快速设置：</span><button type="button" onClick={()=>extendHabit(4,0)}>4 周</button><button type="button" onClick={()=>extendHabit(8,0)}>8 周</button><button type="button" onClick={()=>extendHabit(0,1)}>1 个月</button><button type="button" onClick={()=>extendHabit(0,3)}>3 个月</button></div><Actions onDelete={()=>{setHabits(habits.filter(h=>h.id!==habitEdit.id));setHabitEdit(null)}} onCancel={()=>setHabitEdit(null)} onSave={()=>{if(habitEdit.title.trim()&&habitEdit.startDate&&habitEdit.endDate)setHabits([...habits.filter(h=>h.id!==habitEdit.id),habitEdit]);setHabitEdit(null)}}/></Modal>}
  {ideaEdit&&<Modal title={ideaEdit.title||'记一个念头'} onClose={()=>setIdeaEdit(null)}><label>是什么<input autoFocus value={ideaEdit.title} onChange={e=>setIdeaEdit({...ideaEdit,title:e.target.value})} placeholder="一句话就够了"/></label><label>放在哪里<select value={ideaEdit.category} onChange={e=>setIdeaEdit({...ideaEdit,category:e.target.value as Idea['category']})}><option>想法</option><option>书</option><option>电影</option><option>文章</option><option>人生思考</option></select></label><label>多写一点<textarea value={ideaEdit.note} onChange={e=>setIdeaEdit({...ideaEdit,note:e.target.value})} placeholder="为什么对它感兴趣？以后想从哪里继续？"/></label><Actions onDelete={()=>{setIdeas(ideas.filter(i=>i.id!==ideaEdit.id));setIdeaEdit(null)}} onCancel={()=>setIdeaEdit(null)} onSave={()=>{if(ideaEdit.title.trim())setIdeas([...ideas.filter(i=>i.id!==ideaEdit.id),ideaEdit]);setIdeaEdit(null)}}/></Modal>}
  {milestoneEdit&&<Modal title="编辑近期节点" onClose={()=>setMilestoneEdit(null)}><label>日期或阶段<input autoFocus value={milestoneEdit.date} onChange={e=>setMilestoneEdit({...milestoneEdit,date:e.target.value})} placeholder="例如：9.10–13"/></label><label>节点内容<input value={milestoneEdit.title} onChange={e=>setMilestoneEdit({...milestoneEdit,title:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={milestoneEdit.hot} onChange={e=>setMilestoneEdit({...milestoneEdit,hot:e.target.checked})}/>标记为高强度时期</label><Actions onDelete={()=>{setMilestones(milestones.filter(m=>m.id!==milestoneEdit.id));setMilestoneEdit(null)}} onCancel={()=>setMilestoneEdit(null)} onSave={()=>{if(milestoneEdit.title.trim())setMilestones([...milestones.filter(m=>m.id!==milestoneEdit.id),milestoneEdit]);setMilestoneEdit(null)}}/></Modal>}
 </main>
}

function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="modal-backdrop" onMouseDown={onClose}><form className={'course-editor '+(wide?'wide-editor':'')} onSubmit={e=>e.preventDefault()} onMouseDown={e=>e.stopPropagation()}><p className="eyebrow">EDIT · 编辑</p><h3>{title}</h3>{children}</form></div>}
function Actions({onDelete,onCancel,onSave}:{onDelete:()=>void;onCancel:()=>void;onSave:()=>void}){return <div className="editor-actions"><button type="button" className="delete" onClick={onDelete}>删除</button><button type="button" onClick={onCancel}>取消</button><button type="button" className="primary" onClick={onSave}>保存</button></div>}
