import {useEffect,useMemo,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import {DAYS,addDays,bufferOccupations,courseConflicts,courseLanes,coursePeriodLabel,courseSegments,termConflicts,workplaceSessions,dateKey,monday,newId,noteReminders,parseDate,periodRow,schoolCourses,termWeek,validCourse,validDate,weekCourses} from './planner';
import type {Course,Habit,Idea,Milestone,Planner,Project,Task} from './planner';
export {Editors} from './editors';
export type Editor={kind:'task';value:Task}|{kind:'project';value:Project}|{kind:'habit';value:Habit}|{kind:'milestone';value:Milestone}|{kind:'idea';value:Idea};
export type Update=(fn:(d:Planner)=>Planner)=>void;
export type Checkpoint=(fn:(d:Planner)=>Planner,message:string)=>void;
const periods=coursePeriodLabel;
const fmt=(d:Date)=>`${d.getMonth()+1}/${d.getDate()}`;

export function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:ReactNode;wide?:boolean}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close()},[]);
  return <dialog ref={ref} className={'modal '+(wide?'wide':'')} aria-label={title} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose()}}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="关闭" onClick={onClose}>×</button></div>{children}</dialog>;
}
export function Actions({onDelete,onSave}:{onDelete:()=>void;onSave:()=>void}){return <div className="editor-actions"><button className="text-button delete-button" onClick={onDelete}>删除</button><button className="primary" onClick={onSave}>保存</button></div>}

export function Schedule({data,now,update,setNotice,setEditor}:{data:Planner;now:Date;update:Update;setNotice:(s:string)=>void;setEditor:(e:Editor|null)=>void}){
  const [date,setDate]=useState(()=>dateKey(now)),[layout,setLayout]=useState<'day'|'week'>('day');
  const [edit,setEdit]=useState<Course|null>(null),[selected,setSelected]=useState<Course|null>(null),[noteOpen,setNoteOpen]=useState(false),[syncOpen,setSyncOpen]=useState(false);
  const day=parseDate(date),start=monday(day),key=dateKey(start),courses=weekCourses(data,day),conflicts=courseConflicts(courses);
  const places=workplaceSessions(data,day).filter(p=>layout==='week'||p.day===(day.getDay()||7));
  const lanes=courseLanes(courses),allConflicts=useMemo(()=>termConflicts(data),[data]),buffers=useMemo(()=>bufferOccupations(data),[data]);
  const dayCourses=courses.filter(c=>c.day===(day.getDay()||7)),noteKey=selected?`${date}:${selected.title}`:'';
  const save=(next:Course[])=>update(d=>({...d,schedules:{...d.schedules,[key]:next.filter(c=>c.kind!=='habit')}}));
  const open=(c:Course)=>{setSelected(c);setNoteOpen(false)};
  const editCourse=(c:Course)=>{if(c.kind==='habit'){const h=data.habits.find(h=>h.id===c.habitId);if(h)setEditor({kind:'habit',value:{...h}});setSelected(null)}else{setEdit({...c});setSelected(null)}};
  return <>
    <div className="page-heading"><div><p className="eyebrow">{termWeek(day,data.termStart)>0?`秋季学期 · 第 ${termWeek(day,data.termStart)} 周`:'开学前'}</p><h1>{layout==='day'?`${fmt(day)} ${DAYS[(day.getDay()||7)-1]}`:`${fmt(start)} — ${fmt(addDays(start,6))}`}</h1></div><div className="segmented"><button aria-pressed={layout==='day'} onClick={()=>setLayout('day')}>当天</button><button aria-pressed={layout==='week'} onClick={()=>setLayout('week')}>整周</button></div></div>
    <div className="schedule-toolbar"><button aria-label={layout==='day'?'前一天':'上一周'} onClick={()=>setDate(dateKey(addDays(day,layout==='day'?-1:-7)))}>←</button><button onClick={()=>setDate(dateKey(now))}>{layout==='day'?'今天':'本周'}</button><button aria-label={layout==='day'?'后一天':'下一周'} onClick={()=>setDate(dateKey(addDays(day,layout==='day'?1:7)))}>→</button><input aria-label="跳转日期" type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/><button onClick={()=>setEdit({id:newId(),day:day.getDay()||7,period:1,span:1,title:'',kind:'self',location:''})}>＋ 自己的安排</button></div>
    {places.length>0&&<details className="inline-details" open={layout==='day'}><summary>工位时段</summary><div className="workplace-strip">{places.map(p=><div key={p.day+':'+p.period}><strong>{DAYS[p.day-1]} · {p.label}</strong><small>{p.note}</small></div>)}</div></details>}
    <details className="inline-details term-check"><summary>本学期检查 · {allConflicts.length} 处重叠{buffers.length>0?` · ${buffers.length} 处占用预留空白`:''}</summary><p className="muted">逐周检查当前浏览器中的学校课程和个人安排，覆盖学期前 19 周。固定安排到 1 月 17 日；周三下午、周日不额外加任务。实际调课后会重新计算。结课后的原上课时段留空，已有学习块继续保留。</p>{allConflicts.map((item,i)=><button className="list-row" key={'conflict'+i} onClick={()=>{setDate(item.date);setLayout('day')}}><span><strong>{item.date} · {DAYS[item.first.day-1]}</strong><small>{item.first.title}（{periods(item.first)}）与 {item.second.title}（{periods(item.second)}）</small></span><span>查看 ›</span></button>)}{!allConflicts.length&&<p>目前未发现时间重叠。</p>}{buffers.length>0&&<><h3>预留空白里的已有安排</h3>{buffers.map((item,i)=><button className="list-row" key={'buffer'+i} onClick={()=>{setDate(item.date);setLayout('day')}}>{item.date} · {item.course.title} · {periods(item.course)} ›</button>)}</>}<p className="muted">未明确节次的时段暂按：周二下午 6–7 节，周五科研 3–5 节，周六游泳 8–9 节、上机 11–14 节；周三、周四跑步休息 13–14 节。点击安排可以调整。</p></details>
    {conflicts.length>0&&<details className="conflict-note"><summary>有安排重叠，展开后可以调整</summary>{conflicts.map(c=><button className="list-row" key={c.kind+c.id} onClick={()=>editCourse(c)}>{DAYS[c.day-1]} {periods(c)} · {c.title}</button>)}</details>}
    {layout==='day'?<div className="day-courses">{dayCourses.length?dayCourses.map(c=><button className={'day-course '+c.kind} key={c.kind+c.id} onClick={()=>open(c)}><span className="course-period">{periods(c)}</span><span><strong>{c.title}</strong><small>{c.location|| (c.kind==='habit'?'固定安排':'自己的安排')}</small></span><span>›</span></button>):<div className="surface empty-day"><h2>这一天留有空白</h2><p>没有排课或自己的安排。</p></div>}</div>:<div className="schedule-scroll"><div className="schedule-grid"><div className="grid-corner">节次</div>{DAYS.map((name,i)=><div key={name} className={'day-heading '+(dateKey(addDays(start,i))===dateKey(now)?'is-today':'')} style={{gridColumn:i+2,gridRow:1}}><b>{name}</b><small>{fmt(addDays(start,i))}</small></div>)}{Array.from({length:14},(_,i)=><div className="period-heading" key={i} style={{gridColumn:1,gridRow:periodRow(i+1)}}>{i+1}</div>)}<div className="schedule-break" style={{gridRow:7}}>午间休息</div><div className="schedule-break" style={{gridRow:13}}>晚间休息</div>{Array.from({length:14},(_,i)=>DAYS.map((name,j)=><button className="schedule-slot" key={`${i}-${j}`} aria-label={`${name}第${i+1}节添加安排`} style={{gridColumn:j+2,gridRow:periodRow(i+1)}} onClick={()=>setEdit({id:newId(),day:j+1,period:i+1,span:1,title:'',kind:'self'})}/>))}{courses.flatMap(c=>courseSegments(c).map(segment=><button className={'course-block '+c.kind+(c.breakTime?' break-block':'')+(conflicts.includes(c)?' has-conflict':'')} key={`${c.kind}-${c.id}-${segment.row}`} style={{gridColumn:c.day+1,gridRow:`${segment.row} / span ${segment.span}`,width:`calc(${100/(lanes.get(c)?.count??1)}% - 6px)`,marginLeft:`calc(${100*(lanes.get(c)?.lane??0)/(lanes.get(c)?.count??1)}% + 3px)`}} onClick={()=>{setDate(dateKey(addDays(start,c.day-1)));open(c)}}><strong>{c.title}{segment.continuation?'（续）':''}</strong><small>{c.location||(c.kind==='habit'?'固定安排':'')}</small></button>))}</div></div>}
    {layout==='day'&&noteReminders(data,date).filter(n=>n.when==='tomorrow').map((note,i)=><div className="date-note" key={'advance'+i}><span>次日 · {note.eventDate}</span><strong>{note.title}</strong>{note.preparation&&<p>{note.preparation}</p>}</div>)}
    {Object.entries(data.dayNotes).filter(([d])=>layout==='day'?d===date:d>=key&&d<=dateKey(addDays(start,6))).map(([d,notes])=>notes.map((note,i)=><div className="date-note" key={d+i}><span>{d} · 当天安排</span><strong>{note}</strong><button className="text-button" aria-label={'删除当天提醒：'+note} onClick={()=>update(state=>({...state,dayNotes:{...state.dayNotes,[d]:state.dayNotes[d].filter((_,index)=>index!==i)}}))}>删除</button></div>))}
    <div className="schedule-footer"><span>按学校节次显示 · 午间与晚间留白</span><button className="text-button" onClick={()=>setSyncOpen(true)}>更新学校课程</button></div>
    {selected&&<Modal title={selected.title} onClose={()=>setSelected(null)}><p>{DAYS[selected.day-1]} · {periods(selected)}</p>{selected.note&&<p className="muted">{selected.note}</p>}{selected.location&&<p className="location-label">{selected.location}</p>}{selected.teacher&&<p className="muted">授课教师：{selected.teacher}</p>}<button onClick={()=>editCourse(selected)}>{selected.kind==='habit'?'修改固定安排':'调整这一次'}</button>{selected.kind==='course'&&<><button className="text-button" onClick={()=>setNoteOpen(v=>!v)}>记一句课程笔记</button>{noteOpen&&<label>学到哪里 / 疑问 / 作业（选一项记就好）<textarea value={data.courseNotes[noteKey]??''} onChange={e=>update(d=>({...d,courseNotes:{...d.courseNotes,[noteKey]:e.target.value}}))} placeholder="自动保存，不必填满"/></label>}<details className="inline-details"><summary>这门课之前的记录</summary>{Object.entries(data.courseNotes).filter(([k,v])=>k.endsWith(':'+selected.title)&&v).sort(([a],[b])=>b.localeCompare(a)).map(([k,v])=><div className="course-note" key={k}><small>{k.slice(0,10)}</small><p>{v}</p></div>)}</details></>}</Modal>}
    {edit&&<Modal title="调整本周安排" onClose={()=>setEdit(null)}><label>名称<input value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>星期<select value={edit.day} onChange={e=>setEdit({...edit,day:Number(e.target.value)})}>{DAYS.map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label><div className="form-row"><label>开始节次<input type="number" min="1" max="14" value={edit.period} onChange={e=>setEdit({...edit,period:Number(e.target.value)})}/></label><label>持续节数<input type="number" min="1" max="14" value={edit.span} onChange={e=>setEdit({...edit,span:Number(e.target.value)})}/></label></div><label>地点<input value={edit.location??''} onChange={e=>setEdit({...edit,location:e.target.value})}/></label><label>类型<select value={edit.kind} onChange={e=>setEdit({...edit,kind:e.target.value as Course['kind']})}><option value="self">自己的安排</option><option value="course">学校课程</option></select></label><p className="muted">只修改这一周。跨午休、晚饭的安排会分段显示。</p><Actions onDelete={()=>{save(courses.filter(c=>c.kind==='habit'||c.id!==edit.id));setEdit(null)}} onSave={()=>{if(!validCourse(edit)){setNotice('请填写名称，并把节次设在 1–14 节内。');return}save([...courses.filter(c=>c.kind==='habit'||c.id!==edit.id),edit]);setEdit(null)}}/></Modal>}
    {syncOpen&&<Modal title="统一更新学校课程" onClose={()=>setSyncOpen(false)}><p>所有周的学校课程将按新课表重新生成。自己的安排、习惯和笔记会保留；手动调整过的学校课程会被替换。</p><button className="primary" onClick={()=>{update(d=>({...d,schedules:Object.fromEntries(Object.entries(d.schedules).map(([k,cs])=>[k,[...schoolCourses(parseDate(k),d.termStart),...cs.filter(c=>c.kind==='self')]]))}));setSyncOpen(false);setNotice('学校课程已统一为新课表，自己的安排已保留。')}}>更新学校课程</button></Modal>}
  </>;
}

export function ProjectList({data,today,setEditor,beginProject}:{data:Planner;today:string;setEditor:(e:Editor|null)=>void;beginProject:(p:Project)=>void}){
  return <><div className="page-heading"><div><p className="eyebrow">不绝如缕</p><h1>从上次的地方继续</h1></div><button onClick={()=>setEditor({kind:'project',value:{id:newId(),name:'',color:'#63745c',mainline:'',note:'',todos:[],status:'active',progress:'',next:''}})}>新项目</button></div>
    <div className="project-list">{data.projects.filter(p=>p.status!=='done').map(p=><article className="project-card" key={p.id}><div className="section-heading"><h2>{p.name}</h2><button className="text-button" onClick={()=>setEditor({kind:'project',value:{...p,todos:p.todos.map(t=>({...t}))}})}>编辑</button></div><p className="muted">{p.status==='waiting'?'等待中':p.status==='paused'?'暂时放下':'进行中'}{p.revisit?` · ${p.revisit} 再看`:''}</p>{p.progress&&<p><span className="field-caption">当前进展</span>{p.progress}</p>}{p.status==='waiting'&&p.waiting?<p><span className="field-caption">等待什么</span>{p.waiting}</p>:<p><span className="field-caption">下一步</span>{p.next||p.mainline||'打开项目，留下一句下次从哪里继续。'}</p>}<button onClick={()=>beginProject(p)}>接着做</button></article>)}{!data.projects.some(p=>p.status!=='done')&&<p className="empty-note">项目可以从一句“下一步”开始。</p>}</div>
    <details className="drawer"><summary>近期安排与截止</summary><div className="drawer-content"><p className="muted">设置“开始处理日期”，到那一天才会在首页安静提示。截止当天和已过期事项会保留提示，直到你确认。</p><button onClick={()=>setEditor({kind:'milestone',value:{id:newId(),title:'',date:today,hot:false,action:'',actionDate:today}})}>添加安排</button>{data.milestones.filter(m=>!m.done).sort((a,b)=>a.date.localeCompare(b.date)).map(m=><button className="list-row" key={m.id} onClick={()=>setEditor({kind:'milestone',value:{...m}})}><span><strong>{m.title}</strong><small>{m.action||'尚未填写下一步'}</small></span><span>{m.date}{!validDate(m.date)&&' · 请确认日期'}</span></button>)}</div></details>
    <details className="drawer"><summary>习惯与自己的安排</summary><div className="drawer-content"><button onClick={()=>setEditor({kind:'habit',value:{id:newId(),title:'',day:1,period:1,span:1,startDate:today,endDate:dateKey(addDays(parseDate(today),27))}})}>添加习惯</button>{data.habits.map(h=><button className="list-row" key={h.id} onClick={()=>setEditor({kind:'habit',value:{...h}})}><span><strong>{h.title}</strong><small>{DAYS[h.day-1]} · {periods({...h,kind:'habit'})}{h.location?` · ${h.location}${h.locationDates?'（指定日期）':''}`:''}</small></span><span>{h.startDate} — {h.endDate}</span></button>)}</div></details>
    <details className="drawer"><summary>已完成的项目和安排</summary><div className="drawer-content">{data.projects.filter(p=>p.status==='done').map(p=><button className="list-row" key={p.id} onClick={()=>setEditor({kind:'project',value:{...p}})}>{p.name}</button>)}{data.milestones.filter(m=>m.done).map(m=><button className="list-row" key={m.id} onClick={()=>setEditor({kind:'milestone',value:{...m}})}>{m.title} · {m.date}</button>)}</div></details>
  </>;
}

export function Records({data,today,update,checkpoint,setEditor,complete,openReview}:{data:Planner;today:string;update:Update;checkpoint:Checkpoint;setEditor:(e:Editor|null)=>void;complete:(t:Task,done:boolean)=>void;openReview:()=>void}){
  const [date,setDate]=useState(today),[input,setInput]=useState('');
  return <><div className="page-heading"><div><p className="eyebrow">我的来路</p><h1>留下的事情都在这里</h1></div><label className="date-picker">查看日期<input aria-label="记录日期" type="date" value={date} max={today} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label></div>
    <section className="surface"><h2>这一天的记录</h2>{data.tasks.filter(t=>t.done&&t.completedAt===date).map(t=><div className="record-row" key={t.id}><span className="record-mark">✓</span><span><strong>{t.step||t.title}</strong><small>{t.project}{t.step?' · '+t.title:''}</small></span><button className="text-button" onClick={()=>complete(t,false)}>撤销完成</button></div>)}{(data.evidence[date]??[]).map((item,i)=><div className="record-row" key={i}><span className="record-mark">·</span><span>{item}</span><button className="text-button" aria-label={'删除记录：'+item} onClick={()=>checkpoint(d=>({...d,evidence:{...d.evidence,[date]:(d.evidence[date]??[]).filter((_,index)=>index!==i)}}),'记录已移除，可撤销。')}>删除</button></div>)}{!data.tasks.some(t=>t.done&&t.completedAt===date)&&!data.evidence[date]?.length&&<p className="empty-note">这里还没有记录。想留一句时再写。</p>}<form className="capture" onSubmit={e=>{e.preventDefault();if(!input.trim())return;update(d=>({...d,evidence:{...d.evidence,[date]:[...(d.evidence[date]??[]),input.trim()]}}));setInput('')}}><input aria-label="记一件发生的事" placeholder="记一件发生的事" value={input} onChange={e=>setInput(e.target.value)}/><button>记下</button></form></section>
    {data.reviews[date]&&<section className="surface"><h2>那天的复盘</h2>{data.reviews[date].note&&<p>{data.reviews[date].note}</p>}<span className="field-caption">留给下次的一句话</span><p>{data.reviews[date].next||'那天没有填写下一步。'}</p>{data.reviews[date].feeling&&<p className="muted">{data.reviews[date].feeling}</p>}{date===today&&<button onClick={openReview}>编辑复盘</button>}</section>}
    {!!data.checkins[date]?.length&&<details className="drawer"><summary>以前留下的打卡</summary><p>{data.checkins[date].join('、')}</p></details>}
    <details className="drawer"><summary>想法、书和生活里的期待</summary><div className="drawer-content"><button onClick={()=>setEditor({kind:'idea',value:{id:newId(),title:'',category:'想法',note:''}})}>记一个想法</button>{data.ideas.map(i=><button className="list-row" key={i.id} onClick={()=>setEditor({kind:'idea',value:{...i}})}><span><strong>{i.title}</strong><small>{i.note||i.category}</small></span><span>{i.category}</span></button>)}</div></details>
  </>;
}
